### ISSUE TITLE
PlayerDamage:is_friendly_fire() causes TeamAI and (sometimes) Player to not take damage

### ISSUE THREAD

**Issue by gr1n-the-big-floppa** [mrcreepysos/Eclipse-Difficulty#25]
PlayerDamage:is_friendly_fire() doesn't correctly determine if TeamAI is being shot by friendlies, resulting in TeamAI not taking damage from cops at all with Pro-Job disabled. Also, this function uses "friendly_fire" variable, but it's supposed to first declared with "local", otherwise "friendly_fire" is a global variable. This can be a reason why sometimes Player stops taking any damage too.

From my testing, making "friendly_fire" a local variable and removing elseif check at line 214 in playerdamage.lua, seems to fix player's invincibility. This, however, makes TeamAI to take friendly fire damage with Pro-Jobs disabled again.

**Comment by rockymoto517** [comment]
Good call, I didn't realize I forgot to declare it as a local variable. I can't test it at the moment, but it looks like if we declare friendly_fire locally and initialize is at false, it should fix this issue. 

Thanks again for finding the bug!
